# Generated by Django 5.2.8 on 2025-11-27 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_diente', models.IntegerField(help_text='Numeración ISO (Ej: 11, 18, 21...)')),
                ('estado', models.CharField(choices=[('Sano', 'Sano'), ('Caries', 'Caries'), ('Obturado', 'Obturado (Relleno)'), ('Ausente', 'Ausente/Extraído'), ('Endodoncia', 'Endodoncia Realizada'), ('Corona', 'Corona'), ('Implante', 'Implante'), ('A_Extraer', 'Indicado para Extracción')], default='Sano', max_length=30)),
                ('cara_diente', models.CharField(blank=True, help_text='Ej: Mesial, Distal, Oclusal (Opcional)', max_length=50, null=True)),
                ('notas', models.CharField(blank=True, help_text='Detalles específicos del problema', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Diente',
                'verbose_name_plural': 'Dientes',
            },
        ),
        migrations.AddField(
            model_name='administrador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='admins/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='doctores/'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='dientes_afectados',
            field=models.ManyToManyField(blank=True, related_name='tratamientos', to='task.diente'),
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones_generales', models.TextField(blank=True, help_text='Ej: Paciente con bruxismo general', null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odontograma', to='task.paciente')),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
            },
        ),
        migrations.AddField(
            model_name='diente',
            name='odontograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dientes', to='task.odontograma'),
        ),
        migrations.AlterUniqueTogether(
            name='diente',
            unique_together={('odontograma', 'numero_diente')},
        ),
    ]
