# Generated by Django 5.2.8 on 2025-11-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_diente_administrador_foto_perfil_doctor_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
        migrations.AlterModelOptions(
            name='diente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historialmedico',
            options={},
        ),
        migrations.AlterModelOptions(
            name='odontograma',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tratamiento',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='diente',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cita',
            name='notas_cancelacion',
        ),
        migrations.RemoveField(
            model_name='historialmedico',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='observaciones_generales',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='dientes_afectados',
        ),
        migrations.AddField(
            model_name='odontograma',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.doctor'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.paciente'),
        ),
        migrations.AlterField(
            model_name='diente',
            name='cara_diente',
            field=models.CharField(blank=True, help_text='Ej: Mesial, Distal', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diente',
            name='estado',
            field=models.CharField(default='Sano', max_length=50),
        ),
        migrations.AlterField(
            model_name='diente',
            name='numero_diente',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diente',
            name='odontograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.odontograma'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.cita'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.doctor'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.paciente'),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.paciente'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='nombre_tratamiento',
            field=models.CharField(choices=[('Cirugía terceros molares', 'Cirugía de terceros molares'), ('Cirugía simple', 'Cirugía simple'), ('Cirugía dientes retenidos', 'Cirugía de dientes retenidos'), ('Implantes', 'Implantes'), ('Curaciones', 'Curaciones'), ('Protesis fija', 'Prótesis fija'), ('Protesis removible', 'Prótesis removible'), ('Limpieza', 'Limpieza'), ('Fluorizaciones', 'Fluorizaciones'), ('Conducto uniradicular', 'Tratamiento conducto uniradicular'), ('Conducto biradicular', 'Tratamiento conducto biradicular'), ('Conducto multiradicular', 'Tratamiento conducto multiradicular'), ('Ortodoncia', 'Ortodoncia'), ('Ortopedia', 'Ortopedia'), ('Botox', 'Botox'), ('Rinomodelacion', 'Rinomodelación'), ('Relleno labios', 'Relleno de labios'), ('PRP', 'Plasma rico en plaquetas'), ('Bioestimuladores', 'Bioestimuladores de colágeno'), ('Hilos PDO', 'Hilos de PDO'), ('PDRN y exosomas', 'PDRN y exosomas')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='diente',
            name='notas',
        ),
    ]
