# Generated by Django 5.2.8 on 2025-11-27 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_administrador_options_alter_cita_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diente',
            options={'ordering': ['numero_diente']},
        ),
        migrations.AlterUniqueTogether(
            name='diente',
            unique_together={('odontograma', 'numero_diente')},
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='diente',
            name='cara_distal',
            field=models.CharField(choices=[('SANO', 'Sano (Sin marcas)'), ('C', 'Caries (Rojo)'), ('DO', 'Diente Obturado (Azul)'), ('X', 'Exodoncia/Ausente (Cruz Roja)'), ('CO', 'Corona (Azul)'), ('TC', 'Tratamiento de Conducto (Azul)'), ('IP', 'Implante (Azul)'), ('P', 'Puente')], default='SANO', max_length=10, verbose_name='Derecha'),
        ),
        migrations.AddField(
            model_name='diente',
            name='cara_lingual',
            field=models.CharField(choices=[('SANO', 'Sano (Sin marcas)'), ('C', 'Caries (Rojo)'), ('DO', 'Diente Obturado (Azul)'), ('X', 'Exodoncia/Ausente (Cruz Roja)'), ('CO', 'Corona (Azul)'), ('TC', 'Tratamiento de Conducto (Azul)'), ('IP', 'Implante (Azul)'), ('P', 'Puente')], default='SANO', max_length=10, verbose_name='Abajo'),
        ),
        migrations.AddField(
            model_name='diente',
            name='cara_mesial',
            field=models.CharField(choices=[('SANO', 'Sano (Sin marcas)'), ('C', 'Caries (Rojo)'), ('DO', 'Diente Obturado (Azul)'), ('X', 'Exodoncia/Ausente (Cruz Roja)'), ('CO', 'Corona (Azul)'), ('TC', 'Tratamiento de Conducto (Azul)'), ('IP', 'Implante (Azul)'), ('P', 'Puente')], default='SANO', max_length=10, verbose_name='Izquierda'),
        ),
        migrations.AddField(
            model_name='diente',
            name='cara_oclusal',
            field=models.CharField(choices=[('SANO', 'Sano (Sin marcas)'), ('C', 'Caries (Rojo)'), ('DO', 'Diente Obturado (Azul)'), ('X', 'Exodoncia/Ausente (Cruz Roja)'), ('CO', 'Corona (Azul)'), ('TC', 'Tratamiento de Conducto (Azul)'), ('IP', 'Implante (Azul)'), ('P', 'Puente')], default='SANO', max_length=10, verbose_name='Centro'),
        ),
        migrations.AddField(
            model_name='diente',
            name='cara_vestibular',
            field=models.CharField(choices=[('SANO', 'Sano (Sin marcas)'), ('C', 'Caries (Rojo)'), ('DO', 'Diente Obturado (Azul)'), ('X', 'Exodoncia/Ausente (Cruz Roja)'), ('CO', 'Corona (Azul)'), ('TC', 'Tratamiento de Conducto (Azul)'), ('IP', 'Implante (Azul)'), ('P', 'Puente')], default='SANO', max_length=10, verbose_name='Arriba'),
        ),
        migrations.AddField(
            model_name='diente',
            name='estado_general',
            field=models.CharField(choices=[('SANO', 'Sano (Sin marcas)'), ('C', 'Caries (Rojo)'), ('DO', 'Diente Obturado (Azul)'), ('X', 'Exodoncia/Ausente (Cruz Roja)'), ('CO', 'Corona (Azul)'), ('TC', 'Tratamiento de Conducto (Azul)'), ('IP', 'Implante (Azul)'), ('P', 'Puente')], default='SANO', max_length=10),
        ),
        migrations.AddField(
            model_name='diente',
            name='notas',
            field=models.TextField(blank=True, help_text='Ej: Caries profunda, requiere endodoncia', null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='odontograma',
            name='observaciones_generales',
            field=models.TextField(blank=True, help_text='Notas generales sobre la boca completa', null=True),
        ),
        migrations.AlterField(
            model_name='diente',
            name='numero_diente',
            field=models.IntegerField(help_text='11 al 85 (ISO)'),
        ),
        migrations.AlterField(
            model_name='diente',
            name='odontograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dientes', to='task.odontograma'),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odontograma', to='task.paciente'),
        ),
        migrations.RemoveField(
            model_name='diente',
            name='cara_diente',
        ),
        migrations.RemoveField(
            model_name='diente',
            name='estado',
        ),
    ]
